### ISSUE TITLE
Plugin activation?

### ISSUE THREAD

**Issue by samwilson** [tierra/wordpress-plugin-tests#5]
I'm probably missing something obvious, but I can't get my plugin to activate under phpunit.

The `tests/bootstrap.php` has:

``` php
// Activates this plugin in WordPress so it can be tested.
$GLOBALS['wp_tests_options'] = array(
    'active_plugins' => array( 'plugin-slug/main-plugin-file.php' ),
);
```

But I think this needs to be followed up with:

``` php
do_action( 'activate_plugin-slug/main-plugin-file.php' );
```

at the end of `tests/bootstrap.php`.

Or am I completely missing the point here? :-) I've done the above and all seems to be working for me.

Thanks!

**Comment by tierra** [comment]
You're right, the `active_plugins` option just treats your plugin as if it was already installed (and activated by the plugin installer), but doesn't actually call the usual plugin activation hooks.

This is the same bootstrap file used for typical plugin-specific unit tests too though, and usually you want to include some tests that ensure activation works correctly, so you might want a separate bootstrap file you use when you run the core WordPress test suite instead of one you would use for your own plugin's test suite which would defer activation within some separate tests.

Really though, it all depends on what your plugin does during activation, and if you'd prefer to make that process part of your bootstrap or not. So I don't bother making the suggestion one way or the other in these skeleton files.

**Comment by samwilson** [comment]
Ah cool, that makes sense.

Still, I wonder if some comment about it mightn't be a good idea, to give people some guidance. :-) Maybe this issue is sufficient!

(Thanks for this repo, by the way! It's helped me lots.)

**Comment by tierra** [comment]
It certainly wouldn't hurt to include the optional suggestion there in the bootstrap file since you mention it. I might add that later.
